namespace Common.Models
{
    public enum BotType
    {
        assault = 1,
        pmcbot = 2,
        marksman = 3,
        bossbully = 4,
        bossgluhar = 5,
        bosskilla = 6,
        bosskojaniy = 7,
        bosssanitar = 8,
        bosstagilla = 9,
        bossstormtrooper = 10,
        followerbully = 11,
        followergluharassault = 12,
        followergluharscout = 13,
        followergluharsecurity = 14,
        followergluharsnipe = 15,
        followerkojaniy = 16,
        followersanitar = 17,
        followerstormtrooper = 18,
        cursedassault = 19,
        sectantpriest = 20,
        sectantwarrior = 21,
        usec = 22,
        exusec = 23,
        gifter = 24,
        bossknight = 25,
        followerbirdeye = 26,
        followerbigpipe = 27,
        bosszryachiy = 28,
        followerzryachiy = 29,
        arenafighterevent = 30,
        crazyassaultevent = 33,
        bossboar = 34,
        followerboar = 35,
        bossboarsniper = 36,
        crazyAssaultEvent = 37,
        peacefullzryachiyevent = 38,
        sectactpriestevent = 39,
        ravangezryachiyevent = 40,
        followerboarclose1 = 41,
        followerboarclose2 = 42,
        bosskolontay = 43,
        followerkolontayassault = 44,
        followerkolontaysecurity = 45,
        shooterbtr = 46,

    }
}
